framework:
    messenger:
        # On supprime ou on commente la ligne failure_transport
        # failure_transport: failed

        transports:
            async: 
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    # On force la compatibilit√© avec votre MariaDB
                    use_skip_locked: false 

        routing:
            # On envoie les emails via le transport "async" (qui est maintenant sync)
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': async