# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.
# See also https://symfony.com/doc/current/service_container/import.html

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            App\Service\Alert\AlertServiceInterface: '@App\Service\Alert\AlertService'
            App\Service\Carbon\CarbonServiceInterface: '@App\Service\Carbon\CarbonService'
            App\Service\Consumption\ConsumptionServiceInterface: '@App\Service\Consumption\ConsumptionService'
            App\Service\Profile\ProfileServiceInterface: '@App\Service\Profile\ProfileService'
            App\Service\Dashboard\DashboardDataServiceInterface: '@App\Service\Dashboard\DashboardDataService'
            App\Service\Form\FormDataExtractorServiceInterface: '@App\Service\Form\FormDataExtractorService'
            App\Service\Appliance\ApplianceDataServiceInterface: '@App\Service\Appliance\ApplianceDataService'
            App\Service\Lodgment\LodgmentServiceInterface: '@App\Service\Lodgment\LodgmentService'
            App\Service\BilanCarbone\BilanCarboneCalculatorServiceInterface: '@App\Service\BilanCarbone\BilanCarboneCalculatorService'
            App\Service\User\UserRegistrationServiceInterface: '@App\Service\User\UserRegistrationService'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Configuration des interfaces et leurs implémentations
    # Définir les services concrets comme privés
    App\Service\Alert\AlertService:
        public: false

    App\Service\Carbon\CarbonService:
        public: false

    App\Service\Consumption\ConsumptionService:
        public: false

    App\Service\Profile\ProfileService:
        public: false

    App\Service\Dashboard\DashboardDataService:
        public: false

    App\Service\Form\FormDataExtractorService:
        public: false

    App\Service\Appliance\ApplianceDataService:
        public: false

    App\Service\Lodgment\LodgmentService:
        public: false

    App\Service\BilanCarbone\BilanCarboneCalculatorService:
        public: false

    App\Service\User\UserRegistrationService:
        public: false

    # Créer les alias publics des interfaces vers les implémentations
    App\Service\Alert\AlertServiceInterface: '@App\Service\Alert\AlertService'
    App\Service\Carbon\CarbonServiceInterface: '@App\Service\Carbon\CarbonService'
    App\Service\Consumption\ConsumptionServiceInterface: '@App\Service\Consumption\ConsumptionService'
    App\Service\Profile\ProfileServiceInterface: '@App\Service\Profile\ProfileService'
    App\Service\Dashboard\DashboardDataServiceInterface: '@App\Service\Dashboard\DashboardDataService'
    App\Service\Form\FormDataExtractorServiceInterface: '@App\Service\Form\FormDataExtractorService'
    App\Service\Appliance\ApplianceDataServiceInterface: '@App\Service\Appliance\ApplianceDataService'
    App\Service\Lodgment\LodgmentServiceInterface: '@App\Service\Lodgment\LodgmentService'
    App\Service\BilanCarbone\BilanCarboneCalculatorServiceInterface: '@App\Service\BilanCarbone\BilanCarboneCalculatorService'
    App\Service\User\UserRegistrationServiceInterface: '@App\Service\User\UserRegistrationService'
